# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookparser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='group',
            name='facebook_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='posts',
            name='facebook_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_body',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
