# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookparser', '0005_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='facebook_id',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='administrator',
            field=models.TextField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='cover',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='group',
            name='facebook_id',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='facebook_id',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_body',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
