# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookparser', '0006_auto_20170716_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_body',
            new_name='body',
        ),
    ]
