# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookparser', '0008_auto_20170716_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='facebook_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
