# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookparser', '0009_auto_20170719_1443'),
        ('facebookparser', '0010_auto_20170718_0630'),
    ]

    operations = [
    ]
