# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookparser', '0011_merge_20170725_1840'),
        ('facebookparser', '0010_group_slug'),
    ]

    operations = [
    ]
