# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookparser', '0012_merge_20170910_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='link',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='type',
        ),
        migrations.AddField(
            model_name='group',
            name='test_field',
            field=models.CharField(default='', max_length=200),
        ),
    ]
