# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookparser', '0003_auto_20170710_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='administrator',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
