# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebookparser', '0004_group_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(default='', max_length=100)),
                ('comment', models.CharField(default='', max_length=5000)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebookparser.Posts')),
            ],
        ),
    ]
