# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebookparser', '0007_auto_20170716_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='cover',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='group',
            name='facebook_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
