# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookparser', '0009_auto_20170719_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
    ]
