# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookparser', '0009_auto_20170716_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='facebook_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
