# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookparser', '0013_auto_20171020_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name_test',
            field=models.CharField(default='', max_length=255),
        ),
    ]
